# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multipleFamilyPValue_cpp <- function(sharingProbs, observedSharing, minPValue = 0.0) {
    .Call('_RVS_multipleFamilyPValue_cpp', PACKAGE = 'RVS', sharingProbs, observedSharing, minPValue)
}

multipleVariantPValue_cpp <- function(alleles, variants, famIds, sharingProbs, rfilter, minorAllele, alpha) {
    .Call('_RVS_multipleVariantPValue_cpp', PACKAGE = 'RVS', alleles, variants, famIds, sharingProbs, rfilter, minorAllele, alpha)
}

enrichmentPValue_cpp <- function(snpMat, famIds, sharingProbs, minorAllele, threshold) {
    .Call('_RVS_enrichmentPValue_cpp', PACKAGE = 'RVS', snpMat, famIds, sharingProbs, minorAllele, threshold)
}

